name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # עדכנתי גם פה לגרסה הכי חדשה

      - name: Setup Node.js
        uses: actions/setup-node@v4 # עדכנתי גם פה לגרסה הכי חדשה
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init "SpaceMath" "com.spacemath.app" --web-dir .
          npx cap add android

      - name: Build Android Project
        run: npx cap copy android

      - name: Upload APK
        uses: actions/upload-artifact@v4 # זה התיקון החשוב!
        with:
          name: app-release
          path: android/app/build/outputs/apk/debug/app-debug.apk
